const highlightedMachines = [
  { id: '8107', zone: '拉丝', status: 'normal', order: 'JW-260918-071', product: '0.76mm 镀锌钢丝', material: '盘条 Q195', capacity: '92%', queue: 2, change: '06:30', risk: '无' },
  { id: '8115', zone: '拉丝', status: 'idle', order: '待排', product: '—', material: '盘条 Q195', capacity: '36%', queue: 0, change: '无', risk: '无' },
  { id: '8124', zone: '拉丝', status: 'change', order: 'JW-260918-083', product: '0.95mm 光面钢丝', material: '盘条 65#', capacity: '78%', queue: 5, change: '进行中', risk: '换型剩余 42 分钟' },
  { id: '8204', zone: '捻股', status: 'normal', order: 'JW-260918-102', product: '1+6 B4 股', material: '1.77mm 光面钢丝', capacity: '88%', queue: 3, change: '08:10', risk: '无' },
  { id: '8218', zone: '捻股', status: 'risk', order: 'JW-260918-106', product: '6×29FI 股', material: '2.18mm 镀锌钢丝', capacity: '98%', queue: 8, change: '09:40', risk: '队列拥堵 3.5h' },
  { id: '8231', zone: '捻股', status: 'idle', order: '待排', product: '—', material: '1.65mm 镀锌钢丝', capacity: '41%', queue: 1, change: '无', risk: '无' },
  { id: '8304', zone: '合绳', status: 'risk', order: 'JW-260918-106', product: '30mm GT34Z(35W×K7+WSC)', material: '捻股组件 / WSC 绳芯', capacity: '96%', queue: 6, change: '07:20', risk: '可能影响 2 张订单交期' },
  { id: '8307', zone: '合绳', status: 'normal', order: 'JW-260918-111', product: '22mm GT8ZH', material: '8 股 + IWRC', capacity: '81%', queue: 2, change: '10:30', risk: '无' },
  { id: '8312', zone: '合绳', status: 'change', order: 'JW-260918-118', product: '12mm GT6Z', material: '6 股 + IWRC', capacity: '72%', queue: 4, change: '进行中', risk: '换型需 1.2h' }
];
// 真实设备编号来自《产品额定（平均值）》：47 台拉丝、50 台捻股、12 台合绳。
const deviceIds = {
  拉丝: ['8103','8104','8105','8106','8107','8108','8109','8110','8111','8112','8113','8114','8115','8116','8117','8118','8119','8120','8121','8122','8123','8124','8125','8126','8127','8128','8129','8130','8131','8132','8133','8134','8135','8136','8137','8138','8139','8140','8141','8142','8143','8144','8145','8146','8147','8148','8149'],
  捻股: ['8201','8202','8203','8204','8205','8206','8207','8208','8209','8210','8211','8212','8213','8214','8215','8216','8217','8218','8219','8220','8221','8222','8223','8224','8225','8226','8227','8228','8229','8230','8231','8232','8233','8234','8235','8236','8237','8238','8239','8240','8241','8242','8243','8244','8245','8247','8248','8249','8250','8251'],
  合绳: ['8301','8302','8303','8304','8305','8306','8307','8308','8309','8310','8246','8312']
};
const defaultStateCycle = ['normal','normal','normal','normal','normal','idle','normal','change','normal','normal','idle','normal','normal','risk'];
const makeMachine = (id, zone, index) => ({ id, zone, status: defaultStateCycle[index % defaultStateCycle.length], order: `JW-260918-${String(130 + index).padStart(3,'0')}`, product: zone === '拉丝' ? '镀锌钢丝' : zone === '捻股' ? '标准股型' : '标准钢丝绳', material: zone === '拉丝' ? '盘条 Q195' : '待模型接入', capacity: `${62 + (index * 7) % 30}%`, queue: 1 + index % 5, change: '待模型计算', risk: '无' });
const specialById = Object.fromEntries(highlightedMachines.map(machine => [machine.id, machine]));
const machines = Object.entries(deviceIds).flatMap(([zone, ids]) => ids.map((id, index) => specialById[id] || makeMachine(id, zone, index)));
const tasks = [
  {machine:'8107 拉丝',label:'JW-071',left:4,width:36,status:'normal'}, {machine:'8115 拉丝',label:'待排',left:46,width:18,status:'change'}, {machine:'8124 拉丝',label:'JW-083 · 换型',left:18,width:41,status:'change'},
  {machine:'8204 捻股',label:'JW-102',left:8,width:40,status:'normal'}, {machine:'8218 捻股',label:'JW-106 · 拥堵',left:37,width:51,status:'risk'}, {machine:'8231 捻股',label:'JW-112',left:57,width:25,status:'normal'},
  {machine:'8304 合绳',label:'JW-106 · 临期',left:13,width:66,status:'risk'}, {machine:'8307 合绳',label:'JW-111',left:48,width:30,status:'normal'}, {machine:'8312 合绳',label:'换型中',left:5,width:27,status:'change'}
];
const risks = [
  {level:'risk', title:'8304 合绳机队列拥堵', text:'JW-106 可能延迟 6 小时，影响后续 2 张订单', time:'刚刚', machine:'8304'},
  {level:'change', title:'8124 拉丝机正在换型', text:'规格切换剩余 42 分钟，建议暂缓插入同类急单', time:'20:16', machine:'8124'},
  {level:'risk', title:'JW-260918-126 物料临期', text:'WSC 绳芯库存仅够 1.5 小时生产', time:'19:54', machine:'8304'}
];
const orders = [
  ['订单号','产品规格','数量','交期','状态'],['JW-260918-106','30mm GT34Z','1,600m','09/19 08:00','临期'],['JW-260918-111','22mm GT8ZH','2,000m','09/19 12:00','正常'],['JW-260918-118','12mm GT6Z','1,000m','09/19 16:00','换型中'],['JW-260918-126','28mm GT8PZ','2,000m','09/20 08:00','缺料风险']
];
let selected = machines.find(m => m.id === '8304');
let inserted = false;
const $ = selector => document.querySelector(selector);

function renderPlant(){
  const target = $('#plantMap');
  target.innerHTML = ['拉丝','捻股','合绳'].map(zone => {
    const list = machines.filter(m => m.zone === zone);
    const active = list.filter(m => m.status === 'normal').length;
    const changing = list.filter(m => m.status === 'change').length;
    const atRisk = list.filter(m => m.status === 'risk').length;
    const featured = list.find(m => m.id === (zone === '拉丝' ? '8107' : zone === '捻股' ? '8218' : '8304')) || list[0];
    const samples = [featured, ...list.filter(m => m.id !== featured.id && ['risk','change','idle'].includes(m.status)).slice(0,2)];
    return `<section class="plant-zone zone-${zone}"><div class="zone-top"><span>${zone}工段</span><span><b>${list.length}</b> 台设备</span></div><div class="facility-scene"><div class="facility-track"></div>${samples.map((m,index) => `<button class="scene-machine ${m.status} ${index===0?'focus':''}" data-machine="${m.id}" title="查看 ${m.id} 设备详情"><i></i><strong>${m.id}</strong><small>${m.status==='risk'?'风险':m.status==='change'?'换型':m.status==='idle'?'待排':'生产'}</small></button>`).join('')}<div class="facility-health"><b>${active} 台</b><span>正在生产</span><em>${changing} 换型 · ${atRisk} 风险</em></div></div><p class="zone-summary">点击工段设备查看详情；全部 ${list.length} 台设备可在“设备态势”页查看</p></section>`;
  }).join('');
  target.querySelectorAll('[data-machine]').forEach(button => button.addEventListener('click', () => selectMachine(button.dataset.machine)));
}
function renderGantt(){
  $('#ganttRows').innerHTML = tasks.map(task => `<div class="gantt-row"><label>${task.machine}</label><div class="timeline"><button data-task="${task.machine.slice(0,4)}" class="task ${task.status}" style="left:${task.left}%;width:${task.width}%">${task.label}</button></div></div>`).join('');
  document.querySelectorAll('[data-task]').forEach(button => button.addEventListener('click',()=>selectMachine(button.dataset.task)));
}
function renderRisks(){
  $('#riskList').innerHTML = risks.map(r => `<div class="risk-item" data-risk-machine="${r.machine}"><i class="risk-badge ${r.level}"></i><div><b>${r.title}</b><p>${r.text}</p></div><time>${r.time}</time></div>`).join('');
  document.querySelectorAll('[data-risk-machine]').forEach(item=>item.addEventListener('click',()=>selectMachine(item.dataset.riskMachine)));
}
function renderOrders(){ $('#ordersTable').innerHTML = orders.map((row,i)=>`<div class="order-row">${row.map((cell,j)=>`<span class="${i&&j===4?(cell==='临期'||cell==='缺料风险'?'at-risk':cell==='换型中'?'hot':''):''}">${cell}</span>`).join('')}</div>`).join(''); }
function renderAssistant(){
  const riskText = selected.risk === '无' ? '当前无硬性冲突；保持现有顺序可减少换型。' : selected.risk;
  $('#assistantContent').innerHTML = `
    <section><h3>当前选中</h3><p><b>${selected.id} · ${selected.zone}工段</b><br>${selected.status==='risk'?'风险处理优先':selected.status==='change'?'规格切换中':'按计划运行'} · 利用率 ${selected.capacity}</p></section>
    <section><h3>约束依据</h3><span class="constraint">设备适配</span><span class="constraint">交期优先</span>${selected.status==='change'?'<span class="constraint">换型成本</span>':''}<p>${selected.order==='待排'?'该设备当前空闲，可作为插单的备选产能。':`订单 ${selected.order} 安排在此设备：当前加工 ${selected.product}，可避免额外设备切换。`}</p></section>
    <section><h3>影响评估</h3><p>材料：${selected.material}<br>等待队列：${selected.queue} 项 · 下次换型：${selected.change}<br>${riskText}</p></section>
    <section><h3>建议动作</h3><ul><li>查看同工段可用设备</li><li>${selected.status==='risk'?'将非紧急订单移至 8307 后重新评估':'锁定当前任务，保持排程稳定'}</li><li>进入插单推演对比交期影响</li></ul></section>`;
}
function selectMachine(id){ const next = machines.find(m=>m.id===id); if(!next) return; selected=next; renderAssistant(); document.querySelectorAll('.machine').forEach(e=>e.classList.toggle('selected-machine',e.dataset.machine===id)); showToast(`已定位 ${id}：${next.zone}工段 · ${next.order}`); }
function showToast(message){ const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200); }
function simulateInsert(){
  if(inserted){showToast('紧急插单方案已在推演中');return;}
  inserted=true; const riskMachine=machines.find(m=>m.id==='8304');riskMachine.capacity='100%';riskMachine.queue=7;riskMachine.risk='急单插入后，JW-106 预计顺延 2.5 小时';tasks.push({machine:'8307 合绳',label:'急单 JW-999',left:11,width:28,status:'risk'});risks.unshift({level:'risk',title:'紧急插单 JW-999 已加入推演',text:'8307 接单可守住急单交期；JW-106 将顺延 2.5 小时',time:'现在',machine:'8307'});$('#riskCount').textContent='8';$('#congestedCount').textContent='4';renderGantt();renderRisks();selectMachine('8307');showToast('已生成插单影响方案：请在右侧确认处理动作');
}
function toggleTheme(){document.body.classList.toggle('light');const isLight=document.body.classList.contains('light');localStorage.setItem('production-dashboard-theme',isLight?'light':'dark');$('#themeToggle').textContent=isLight?'◐':'☼';showToast(isLight?'已切换浅色阅读主题':'已切换深色护眼主题');}
const pageMeta = {schedule:['智能排产','设定排产目标、锁定任务并生成可执行计划'],orders:['订单中心','查看订单交期、优先级与工艺匹配状态'],risks:['风险预警','聚焦影响交期与产能承诺的异常'],reschedule:['重排推演','比较插单、停机与物料延迟下的候选方案'],machines:['设备态势','查看 109 台真实设备编号的任务与负荷'],data:['数据管理','导入业务数据并导出排产成果']};
function pageFrame(page, body){const [title,sub]=pageMeta[page];return `<div class="module-header"><div><p class="eyebrow">${sub}</p><h2>${title}</h2></div><button class="primary-button">${page==='data'?'导入 Excel':page==='reschedule'?'新建推演':'导出当前视图'}</button></div>${body}`;}
function schedulePage(){return pageFrame('schedule',`<div class="module-grid"><section class="panel module-card"><div class="panel-heading"><div><p class="eyebrow">优化偏好</p><h2>排产参数</h2></div></div><div class="form-list"><label>优化目标 <select><option>准时交付优先</option><option>平衡交付与换型</option><option>设备利用率优先</option></select></label><label>排产窗口 <select><option>未来 7 天</option><option>未来 14 天</option></select></label><label>已锁定任务 <b>12 项</b></label><button class="primary-button" onclick="document.getElementById('simulateButton').click()">生成试排方案</button></div></section><section class="panel module-card span-2"><div class="panel-heading"><div><p class="eyebrow">候选方案 A</p><h2>设备排程预览</h2></div><span class="good">可执行</span></div><div class="schedule-preview"><div><b>拉丝</b><i style="width:72%"></i><i class="amber" style="width:15%"></i></div><div><b>捻股</b><i style="width:61%"></i><i class="red" style="width:25%"></i></div><div><b>合绳</b><i style="width:82%"></i><i class="amber" style="width:10%"></i></div></div><p class="module-note">预计准时交付率 92.4%，3 台设备存在换型窗口，7 张订单需要计划员确认。</p></section></div>`)}
const orderRows = (items=orders.slice(1)) => items.map((r,i)=>`<div class="order-data" data-order="${r[0]}"><span>${r[0]}</span><span>${r[1]}</span><span>${r[2]}</span><span>${r[3]}</span><span class="${i===0?'danger':''}">${i===0?'紧急':'常规'}</span><span class="good">已匹配</span></div>`).join('') || '<p class="empty-state">没有找到匹配订单</p>';
function ordersPage(){return pageFrame('orders',`<section class="panel module-card"><div class="filter-row"><input id="orderSearch" placeholder="搜索订单号、规格或客户" /><button id="orderRiskFilter">仅看风险</button><button id="orderSort">交期升序 ▾</button><button id="newOrder" class="primary-button">新增订单</button></div><div class="data-table"><div class="data-head"><span>订单号</span><span>规格</span><span>数量</span><span>预发货日</span><span>优先级</span><span>工艺匹配</span></div><div id="orderTableBody">${orderRows()}</div></div></section>`)}
function risksPage(){return pageFrame('risks',`<div class="risk-summary"><div><b>2</b><span>硬风险</span></div><div><b>5</b><span>预警</span></div><div><b>3</b><span>换型影响</span></div><div><b>1</b><span>物料临期</span></div></div><section class="panel module-card"><div class="panel-heading"><div><p class="eyebrow">按影响程度排序</p><h2>待处置风险</h2></div></div><div class="risk-action-list">${risks.map((r,i)=>`<button data-risk-machine="${r.machine}" class="risk-action"><i class="${r.level}"></i><div><b>${r.title}</b><p>${r.text}</p></div><span>${i===0?'立即处理':'查看方案'} →</span></button>`).join('')}</div></section>`)}
function reschedulePage(){return pageFrame('reschedule',`<div class="scenario-grid"><section class="panel module-card scenario selected" data-scenario="insert"><p class="eyebrow">场景 01</p><h2>紧急插单</h2><p>新订单要求在 24 小时内交付。</p><b class="danger">影响 2 张订单</b><button class="primary-button">运行推演</button></section><section class="panel module-card scenario" data-scenario="shutdown"><p class="eyebrow">场景 02</p><h2>设备停机</h2><p>选择设备和预计停机时段，计算替代机台。</p><b class="warning">待选择设备</b><button>配置场景</button></section><section class="panel module-card scenario" data-scenario="material"><p class="eyebrow">场景 03</p><h2>物料延迟</h2><p>评估原材料未到货对下游工序的传播。</p><b class="info">待录入物料</b><button>配置场景</button></section></div><section class="panel module-card compare" id="scenarioCompare"><div><b>方案对比</b><span>当前计划</span><span>交期优先</span><span>低扰动</span></div><div><b>准时交付率</b><span>92.4%</span><span class="good">93.1%</span><span>91.8%</span></div><div><b>受影响订单</b><span>7</span><span>4</span><span class="good">3</span></div></section>`)}
const machineRows = (items=machines) => items.map(m=>`<button class="machine-record" data-machine="${m.id}"><i class="${m.status}"></i><b>${m.id}</b><span>${m.zone}</span><span>${m.order}</span><span>利用率 ${m.capacity}</span><em>${m.status==='normal'?'生产中':m.status==='idle'?'待排':m.status==='change'?'换型中':'风险'}</em></button>`).join('') || '<p class="empty-state">没有符合条件的设备</p>';
function machinesPage(){return pageFrame('machines',`<section class="panel module-card"><div class="filter-row"><input id="machineSearch" placeholder="输入设备编号，例如 8304" /><select id="zoneFilter"><option value="all">全部工段</option><option>拉丝</option><option>捻股</option><option>合绳</option></select><select id="statusFilter"><option value="all">全部状态</option><option value="normal">生产中</option><option value="idle">待排</option><option value="change">换型中</option><option value="risk">风险</option></select></div><div id="machineTable" class="machine-list">${machineRows()}</div></section>`)}
function dataPage(){return pageFrame('data',`<div class="module-grid"><section class="panel module-card upload-card"><p class="eyebrow">导入数据</p><h2>订单与工艺文件</h2><div class="drop-zone">⇅<b>拖入 Excel 文件</b><span id="fileHint">支持订单、设备、工艺、物料数据</span><input id="dataInput" type="file" accept=".xlsx,.xls,.csv" hidden><button id="chooseFile">选择文件</button></div></section><section class="panel module-card"><p class="eyebrow">当前数据源</p><h2>数据状态</h2><div class="source-list"><p><b>订单信息.xlsx</b><span class="good">323 条订单</span></p><p><b>产品额定（平均值）.xlsx</b><span class="good">109 台设备</span></p><p><b>典型质量案例.xlsx</b><span class="warning">5 条案例</span></p></div></section><section class="panel module-card"><p class="eyebrow">导出成果</p><h2>计划包</h2><div class="source-list"><p><b>排产计划表</b><button data-export="CSV">导出 CSV</button></p><p><b>设备甘特图</b><button data-export="PNG">导出 PNG</button></p><p><b>风险处置清单</b><button data-export="XLSX">导出 XLSX</button></p></div></section></div>`)}
function applyOrderFilter(){const query=$('#orderSearch').value.trim().toLowerCase();const onlyRisk=$('#orderRiskFilter').classList.contains('selected');let visible=orders.slice(1).filter(row=>row.join(' ').toLowerCase().includes(query));if(onlyRisk)visible=visible.filter((_,index)=>index===0||index===3);$('#orderTableBody').innerHTML=orderRows(visible);}
function applyMachineFilter(){const query=$('#machineSearch').value.trim();const zone=$('#zoneFilter').value;const status=$('#statusFilter').value;const visible=machines.filter(m=>(!query||m.id.includes(query))&&(zone==='all'||m.zone===zone)&&(status==='all'||m.status===status));$('#machineTable').innerHTML=machineRows(visible);$('#machineTable').querySelectorAll('[data-machine]').forEach(btn=>btn.addEventListener('click',()=>selectMachine(btn.dataset.machine)));}
function setScenario(kind){const content={insert:['紧急插单','新急单安排至 8307 可保证交期，JW-106 将顺延 2.5 小时。','93.1%','4'],shutdown:['设备停机','建议将 8218 的后续队列分流至 8204 与 8231，并锁定已开工任务。','91.6%','6'],material:['物料延迟','WSC 绳芯延迟会影响 8304；建议提前分配现有库存至重点客户订单。','90.8%','5']}[kind];document.querySelectorAll('.scenario').forEach(card=>card.classList.toggle('selected',card.dataset.scenario===kind));$('#scenarioCompare').innerHTML=`<div><b>${content[0]}方案对比</b><span>当前计划</span><span>推荐方案</span><span>低扰动</span></div><div><b>准时交付率</b><span>92.4%</span><span class="good">${content[2]}</span><span>91.8%</span></div><div><b>受影响订单</b><span>7</span><span>${content[3]}</span><span class="good">3</span></div><p class="module-note">${content[1]}</p>`;showToast(`已切换至“${content[0]}”推演方案`);}
function setupModule(page){const view=$('#moduleView');view.querySelectorAll('[data-machine]').forEach(btn=>btn.addEventListener('click',()=>{selectMachine(btn.dataset.machine);showToast(`已选中设备 ${btn.dataset.machine}`)}));view.querySelectorAll('[data-risk-machine]').forEach(btn=>btn.addEventListener('click',()=>{selectMachine(btn.dataset.riskMachine);renderModule('dashboard')}));if(page==='orders'){const search=$('#orderSearch');search.addEventListener('input',applyOrderFilter);$('#orderRiskFilter').addEventListener('click',event=>{event.currentTarget.classList.toggle('selected');applyOrderFilter()});$('#orderSort').addEventListener('click',()=>showToast('订单已按预发货日升序排列'));$('#newOrder').addEventListener('click',()=>showToast('新增订单表单将在接入后端后启用'));}if(page==='machines'){['machineSearch','zoneFilter','statusFilter'].forEach(id=>$('#'+id).addEventListener(id==='machineSearch'?'input':'change',applyMachineFilter));}if(page==='reschedule'){view.querySelectorAll('.scenario').forEach(card=>card.addEventListener('click',()=>setScenario(card.dataset.scenario)));}if(page==='schedule'){view.querySelector('.primary-button').addEventListener('click',()=>{simulateInsert();showToast('已按当前偏好生成新的试排方案')});}if(page==='data'){const input=$('#dataInput');$('#chooseFile').addEventListener('click',()=>input.click());input.addEventListener('change',()=>{const file=input.files[0];if(file){$('#fileHint').textContent=`已选择：${file.name}（${Math.ceil(file.size/1024)} KB），等待解析`;showToast('文件已选择；当前为前端演示模式') }});view.querySelectorAll('[data-export]').forEach(button=>button.addEventListener('click',()=>showToast(`已生成 ${button.dataset.export} 导出任务（演示模式）`)));}}
function renderModule(page){const view=$('#moduleView'), dashboard=$('#dashboardContent');if(page==='dashboard'){dashboard.hidden=false;view.hidden=true;$('#assistantPanel').hidden=false;$('.topbar h1').textContent='生产指挥总览';return;}dashboard.hidden=true;view.hidden=false;$('#assistantPanel').hidden=page==='data';$('.topbar h1').textContent=pageMeta[page][0];view.innerHTML=({schedule:schedulePage,orders:ordersPage,risks:risksPage,reschedule:reschedulePage,machines:machinesPage,data:dataPage}[page])();setupModule(page);}
function init(){if(localStorage.getItem('production-dashboard-theme')==='light'){document.body.classList.add('light');$('#themeToggle').textContent='◐'}renderPlant();renderGantt();renderRisks();renderOrders();renderAssistant();$('#themeToggle').addEventListener('click',toggleTheme);$('#simulateButton').addEventListener('click',simulateInsert);$('#lockTask').addEventListener('click',()=>showToast(`已锁定 ${selected.id} 当前安排，后续重排将保留该任务`));document.querySelectorAll('.kpi-card').forEach(card=>card.addEventListener('click',()=>{if(card.dataset.filter==='risk') selectMachine('8304');if(card.dataset.filter==='congested') selectMachine('8218');else showToast('已应用指标筛选（演示状态）')}));document.querySelectorAll('.nav-item').forEach(item=>item.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(i=>i.classList.remove('active'));item.classList.add('active');renderModule(item.dataset.page)}));}
init();
